version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        ARTIFACTORY_API_KEY:
        ARTIFACTORY_USER:
    command: 'tail -f /dev/null'
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
